version: "3.9"

services:
  fastapi-app:
    image: bohdanbulakh/prodmon-backend
    container_name: prodmon-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: prodmon-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--cleanup"
      - "-i"
      - "60"