version: "3.9"

services:
  agent:
    image: bohdanbulakh/prodmon-agent
    privileged: true
    pid: "host"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc:/host/etc:ro
      - ./.env:/app/.env
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_ETC=/host/etc
